---
- name: Create a working directory
  ansible.builtin.file:
    path: /tmp/kernel
    state: directory

- name: Download kernel source
  ansible.builtin.get_url:
    url: https://mirrors.edge.kernel.org/pub/linux/kernel/v6.x/linux-6.6.58.tar.gz
    dest: /tmp/kernel/linux-6.6.58.tar.gz

- name: Download RT patch
  ansible.builtin.get_url:
    url: https://mirrors.edge.kernel.org/pub/linux/kernel/projects/rt/6.6/patch-6.6.58-rt45.patch.xz
    dest: /tmp/kernel/patch-6.6.58-rt45.patch.xz

- name: Install required tools
  ansible.builtin.apt:
    name:
      - xz-utils
      - patch
    state: present
    update_cache: yes

- name: Unpack kernel source
  ansible.builtin.unarchive:
    src: /tmp/kernel/linux-6.6.58.tar.gz
    dest: /tmp/kernel/
    remote_src: yes

- name: Uncompress RT patch
  ansible.builtin.command:
    cmd: xz -d /tmp/kernel/patch-6.6.58-rt45.patch.xz
    chdir: /tmp/kernel/

- name: Make kernel sources files writable
  ansible.builtin.file:
    path: /tmp/kernel/linux-6.6.58
    mode: 'u+w'
    recurse: true

- name: Apply the RT patch
  ansible.builtin.command:
    cmd: patch -p1 -i /tmp/kernel/patch-6.6.58-rt45.patch
    chdir: /tmp/kernel/linux-6.6.58

