- name: Create ptp4l service file
  ansible.builtin.copy:
    dest: /etc/systemd/system/ptp4l.service
    content: |
      [Unit]
      Description=PTP daemon
      After=network.target

      [Service]
      Type=simple
      ExecStart=/usr/sbin/ptp4l -i enp0s25 -m  # Replace eth0 with your network interface
      Restart=on-failure

      [Install]
      WantedBy=multi-user.target
    mode: '0644'

- name: Create phc2sys service file
  ansible.builtin.copy:
    dest: /etc/systemd/system/phc2sys.service
    content: |
      [Unit]
      Description=PHC to system clock synchronization daemon
      After=network.target

      [Service]
      Type=simple
      ExecStart=/usr/sbin/phc2sys -s enp0s25 -c CLOCK_REALTIME -w -m  # Replace eth0 with your network interface
      Restart=on-failure

      [Install]
      WantedBy=multi-user.target
    mode: '0644'

- name: Reload systemd daemon
  ansible.builtin.systemd:
    daemon_reload: yes

- name: Start and enable ptp4l service
  ansible.builtin.systemd:
    name: ptp4l
    enabled: yes
    state: started

- name: Start and enable phc2sys service
  ansible.builtin.systemd:
    name: phc2sys
    enabled: yes
    state: started
